### ISSUE TITLE
Could not load settings at: sf_options.php

### ISSUE THREAD

**Issue by richcoy** [Geczy/WP-Simple-Settings-Framework#10]
New to this, please help.

I downloaded the zip and placed it directly in my plugin's directory. I added the following to the top of my plugin's main file:

```
add_action( 'init', 'sf_load_settings' );
function sf_load_settings() {
    require 'classes/sf-class-settings.php';
    $settings_framework = new SF_Settings_API($id = 'my_plugin_name', $title = 'My Plugin Title', $menu = 'plugins.php', __FILE__);
    $settings_framework->load_options('sf_options.php');
}
```

It's finding the required classes file but it's having a problem with the sf_options.php file. I'm getting a WordPress Error: >"Could not load settings at: sf_options.php".

I've triple checked the file names.

Could you please advise what I might be doing wrong? Thanks!

**Comment by Geczy** [comment]
Try using an absolute path to sf_options.php

**Comment by richcoy** [comment]
Thank you.
